Feature/like zabo
sparcs-kaist/zabo-front-reactjs pull request #48
Opened 2020-01-22 14:24 UTC by Choiyounseo

pinZabo 기능 완료

2020-01-22 21:00 UTC, jungdj requested changes
변수 이름을 좀 더 명확하게 설정하고 props를 간결하게 정리하면 좋겠습니다.

2020-01-22 21:00 UTC, jungdj commented on src/components/pages/ProfilePage/UserProfilePage.js
> +    username, profilePhoto, groups, description, likesNum, pinsNum,
여기서는 num 보다는 count가 더 적절하지 않을까요?
제 개인적인 의견입니다.

2020-01-22 21:00 UTC, jungdj commented on src/components/pages/ZaboPage/ZaboPage.js
> +  const src = isBookmark ? pinSrc : likeSrc;
isBookmark의 값으로 어떤 타입의 stat box인지 결정하는 것 보다 props에서 type을 받아서 명확하게 작성하는게 좀 더 좋아 보입니다.

2020-01-22 21:00 UTC, jungdj commented on src/components/pages/ZaboPage/ZaboPage.js
> +  num, isBookmark, zaboId, isLiked, isPinned,
아래 코멘트에서 언급한바와 같이 isXX 변수를 여러개 받는 것 보다 type prop을 받아서 조금 더 명시적으로 작성할 수 있을 것 같아요

2020-01-22 21:00 UTC, jungdj commented on src/components/pages/ZaboPage/ZaboPage.js
> +  num, isBookmark, zaboId, isLiked, isPinned,
추가로 type의 prop type은 required로 하면 좋겠습니다.

2020-01-22 21:00 UTC, jungdj commented on src/components/pages/ZaboPage/ZaboPage.js
> +    isBookmark ? throttledPin () : throttledLike ();
throttledAction ('like') 또는 throttledAction[type]으로 코드를 간소화 할 수 있어요.

2020-01-22 21:00 UTC, jungdj commented on src/lib/api/zabo.js
> +export const likeZabo = zaboId => axios.post (`/zabo/${zaboId}/like`).then (res => res.data);
pinZabo와 likeZabo가 토글될 수 있다는 것을 명확하게 표현하면 좋겠습니다.
toggleZaboPin과 toggleZaboLike 정도가 생각나요

2020-01-28 14:09 UTC, Choiyounseo commented on src/components/pages/ProfilePage/UserProfilePage.js
> +    username, profilePhoto, groups, description, likesNum, pinsNum,
pinsCount, likesCount, statsCounts로 변수이름 모두 변경했습니다.

2020-01-28 17:16 UTC, Choiyounseo commented
PR 리뷰 isPinned, isLiked 변수명 제외 적용했습니다.

2020-01-28 18:11 UTC, Choiyounseo commented
develop branch와 merge conflict해결 중이었는데 commit 도중 stylelint에서 막혔어요..

AdminPage/Admin.styled.js lint에러 엄청 뜨는데 커밋 어떻게 하신건가요.....?

2020-01-29 13:39 UTC, jungdj approved these changes

2020-01-29 13:40 UTC, merged

2020-01-29 13:40 UTC, jungdj commented
머지하였습니다!! 👏👏