feat(profileSetting): Add nameInput validate form
sparcs-kaist/zabo-front-reactjs pull request #49
Opened 2020-01-22 19:48 UTC by Choiyounseo

use @material-ui/core/FormControl

2020-01-22 21:01 UTC, jungdj commented
validation function이 삽입되면 머지하겠습니다.

2020-01-22 21:01 UTC, jungdj commented
label이랑 milestone 달아주세요

2020-01-22 21:05 UTC, jungdj requested changes
Input field가 비어있을 때나 유저가 입력중일 때는 validate 함수가 호출되지 않는게 좋습니다.
비어있는 값에서는 validate 함수를 호출하지 않으면 되고 
debounce를 사용하여 유저가 인풋을 입력중일 때는 validate 함수를 delay 시키면 됩니다. 
Form helper에 사용하는 id는 위치나 기능을 명확하게 표현하여 다른 컴퍼넌트의 id와 중복되지 않도록 세팅해주세요.
nameValidate 함수의 호출 위치는 render 내부보다는 onChange 내부가 더 적합해 보입니다.

2020-01-22 23:23 UTC, Choiyounseo commented
유저가 입력중일때도 validate를 체크하는 페이지들도 많지않나요? 이건 디자인의 문제 같아요. 임시로 invalid할시 error form이 하단에 셍성될 수 있도록만 구현해둔거라 이건 cookie가 validate 함수 추가하면서 직접하는게 더 편할거 같아요.

2020-01-28 13:57 UTC, Choiyounseo commented
validate function을 onChange 이후에 부르긴하지만 setState가 제대로 반영되기 이전의 username value값을 이용해서 validate 체크가 이루어 지고 있어요..
마음같아선 useSetState에 onChange 내부에 인풋으로 함수도 받을수 있도록 변경해두고 싶긴한데 물어보는게 나을것 같아서...
어떻게 고치는게 좋을까용

2020-01-28 17:51 UTC, Choiyounseo commented
useSetState부분 변경했던데 merge conflict 직접 해결 해주시죠 ㅎ.ㅎ

2020-02-02 21:51 UTC, merged