Feature/404
sparcs-kaist/zabo-front-reactjs pull request #89
Opened 2020-03-10 16:23 UTC by pa-rang

- 404 not found 페이지 디자인하였습니다.
  - vw 속성으로 반응형 적용하였습니다.
  - 진짜 별거 없지만 비효율적으로 짠 부분 있으면 알려주세용 ㅎㅎ
- 그리고 마감임박자보 없는 경우 보여지는 UI 모바일에 맞춰 글씨 크기 조정하였습니다.

2020-03-15 09:38 UTC, Choiyounseo requested changes
고쳐주세욤

2020-03-15 09:38 UTC, Choiyounseo commented on src/components/pages/NotFound/NotFound.js
> +    </Page.Header>
기존의 <Header /> component를 사용하면 되요. (<Header type="upload" /> 이런식으로...

2020-03-15 09:38 UTC, Choiyounseo commented on src/components/pages/NotFound/NotFound.styled.js
> +Page.Description.Link = styled.a`
styled (Link)를 사용해주세요

2020-03-15 09:38 UTC, Choiyounseo commented on src/components/pages/NotFound/NotFound.styled.js
> +`;
중앙정렬을 하고 싶다면 애매한 숫자값과 vw를 사용하기 보단 flex를 사용하는게 훨씬 깔끔하고 좋을거 같아요.
이 Body width가 특정 윈도우 width에선 좀 좁아서 충분히 넓은 width를 가지고 있어도 글자 문장이 한줄이 아닌 두줄로 나누어 보이는 케이스들이 있어요

2020-03-15 09:38 UTC, Choiyounseo commented on src/components/pages/NotFound/NotFound.styled.js
> +`;
이미지 width를 반응형으로 짜려는건가요? vw보단 %를 사용해주세요

2020-03-15 09:38 UTC, Choiyounseo commented on src/components/pages/NotFound/NotFound.js
> +    </Page.Header>
<Header type="upload" />

2020-03-15 09:39 UTC, Choiyounseo commented on src/components/pages/NotFound/NotFound.js
> +    </Page.Header>
Header component가 이미 있어요. 직접 <>로 작성하려니 여기서 안보이네...
type="upload? search?"를 추가하면 될거에요 찾아보고 추가하면 될듯

2020-03-16 08:05 UTC, jungdj commented
withZABO로 인해서 Cyclic Dependency가 발생하고 있어서 수정하였습니다.

ZaboDetailPage, ZaboEditPage, ZaboCard 컴퍼넌트가 withZabo를 사용하고 있는데 withZABO에서 Not found를 처리하는 별도의 로직 또는 별도의 component가 필요해 보입니다.

2020-05-29 07:11 UTC, merged